GOMOCK.VERSION          := 0.6.0
GOMOCKHANDLER.VERSION   := 1.6.1
GOLANGCI_LINT.VERSION   := v2.6.0
PROTOC.VERSION          := 33.0
PROTOC_GEN.VERSION      := v1.36.10
PROTOC_GEN_GRPC.VERSION := v1.5.1
